server:
 port: ${PORT:8080}

spring:
 application:
  name: Product
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 instance:
  preferIpAddress: true
  leaseRenewalIntervalInSeconds: 5
  metadataMap:
   instanceId: "${spring.application.name}:${random.value}"